---
title: "Challenge"
params:
    topic: "Write helper functions to automate aspects of Bioconductor package development."
    difficulty: "advanced"
    leaders:
        value:
            kevinrue: "Kevin Rue"
    tags:
        - "Writing Packages"
        - "Best Practices"
    duration: "1 hour(s)"
---

```{r, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

`r params$topic`

## Difficulty

`r stringr::str_to_title(params$difficulty)`.

## Challenge leader(s)

```{r, echo=FALSE, results='asis'}
for (github in names(params$leaders)) {
    profile <- sprintf("http://github.com/%s", github)
    cat(sprintf('- %s - <i class="fab fa-github"></i> [%s](%s)\n', params$leaders[[github]], github, profile))
}
```

## Tags

```{r, echo=FALSE, results='asis'}
cat(sprintf("- `%s`\n", sort(params$tags)))
```

## Duration

A minimum of `r params$duration` is recommended for this challenge.

## Notes

- Consider contributing functionality for continuous integration/continuous development.
- Look at [biocthis](https://github.com/lcolladotor/biocthis) first for ideas, enhancements, issues, inspiration, ...
